<!-- 
	This code supports the website  DeepCan.com
  
  Author: Jonathan Calles 8906650 (jcall057@uottawa.ca) and Ahmed Haj Abdel Khaleq 8223727 (ahaja032@uottawa.ca)
	     Last Updated: 2018-04-09

  Advisory:
      This website's development is ongoing. Experimental and non-functional features may result.

	Development History:
		2018-03-15 - Webpage code initiated.
    2018-03-15 - HTML search query form created, and linked to php code.
    2018-03-16 - Succesful proof of concept HTML->PHP->SQL->ServerDatabase->PHP->HTML.
    2018-03-18 - HTML reworked to use the W3 CSS, Credit: www.w3schools.com
    2018-03-18 - Navigation bar added, styled search bar added planned to replace static search form.
    2018-03-19 - Connected index.html to raters.html, Added star ratings to restaurants results list.
    2018-03-19 - Changed the left panel to W3 sidebar that can be toggled. Nav bar now highlights selected page.
    2018-03-20 - Removed sidebar altogether in favour of accadd ordion with filter options.
    2018-03-20 - The W3 search is now connected to the PHP code.
    2018-03-29 - Changed file extension .html -> .php. 
    2018-03-29 - Main body now contains dynamic content generated by PHP file that retrieves the search results.
    2018-04-06 - Updated links to .php files. Search results clickable, leads to individual restaurant page.
    2018-04-06 - Added PHP variables to be referenced by the search handler, variables set by button presses.
    2018-04-07 - Added a drop down option to select restaurant category, saves selection as variable.
    2018-04-08 - Adjusted Layout, added automatic slideshow, added button to add restaurant.
    2018-04-08 - Added log in/out button, toggles a pop-up with further profile options.
    2018-04-08 - Added pop-up with entry fields to add a new restaurant, inserts to database.
    2018-04-09 - Added bar-graph of average prices, search category and sort filters enabled.

  Planned:
    - Add log-in and log-out functions
    - Add the ability to create new login profiles
    - Add sentiment analysis, text mining etc.

-->



<!doctype html>
<html>

  <!-- CONFIGURATIONS -->
  <head>

    <!-- A meta viewport gives the browser instructions on how to control the page's dimensions and scaling. i.e. when viewed on different types of devices -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
  	<!-- This code points to a seperate CSS files which contains all the styling rules for the webpage aesthetics -->
    <link href="w3.css" rel="stylesheet">
    <link href="w3-theme-red.css" rel="stylesheet">
  </head>

  <style>
      .mySlides {display:none;}
  </style>


  <body>

    <!-- HEADER -->
    <!-- The contents at the header of the webpage -->
    <header class="w3-container w3-padding" id="mainHeader">
        
        <!-- LOG IN/OUT POP-UP -->
        <!-- A pop up interface with options to log out/in, and change profile settings -->

              <!-- The button which toggles the pop-up -->
              <button onclick="document.getElementById('profile_login').style.display='block'" class="w3-button w3-display-topright w3-padding" style="width:150px" >
                    LOG OUT/IN
                    <img src="images/rater-001.png" style="width:35px">
              </button>

              <!-- The contents of the log out/in pop-up -->
              <div id="profile_login" class="w3-modal">
                <div class="w3-modal-content w3-card-4">

                    <!-- Header for the log out/in pop-up -->
                    <header class="w3-container w3-theme-d1">
                        <!-- Button to close the pop -->
                        <span onclick="document.getElementById('profile_login').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                        <h2>Your Profile</h2>
                    </header>

                    <!-- Main contents of the log out/in pop-up -->
                    <div class="w3-container">
                      <br>
                      <img src="images/rater-001.png" style="width:80px">
                      <p> You are currently logged in as: <b>William</b></p>

                      <!-- Button to log out -->
                      <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method="get">
                        <button class="w3-button w3-hover-shadow w3-round w3-theme" name="log_out" value="log_out">Log Out</button>
                      </form>
                      <br>
                    </div>


                </div>
              </div>

        <!-- Website name and logo as a main centre piece -->
        <div class="w3-center">
          <h1>Deep Can</h1>
              <img src="images/test-logo.png" alt="Test logo for Image loading" style="width: 120px; height: 120px;">
          <h2>Restaurant Reviews</h2>
        </div>

    </header>

    



    <!-- NAVIGATION BAR -->
    <!-- The contents of the navigation bar under the Header -->
    <div class="w3-bar w3-card w3-theme-d3" style="height:100%">
      <a href="index.php" class="w3-bar-item w3-button w3-padding-16 w3-theme-d1">Home</a>
      <a href="top_rated.php" class="w3-bar-item w3-button w3-padding-16">Top Rated</a>
      <a href="raters.php" class="w3-bar-item w3-button w3-padding-16">Raters</a>
      <a href="restaurant.php" class="w3-bar-item w3-button w3-padding-16">Restaurant</a>
      <div class="w3-dropdown-hover">
        <button class="w3-button w3-padding-16">
            Dropdown
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="w3-dropdown-content w3-card-4 w3-bar-block">
            <a href="insert javascript or url here" class="w3-bar-item w3-button">Link 1</a>
            <a href="insert javascript or url here" class="w3-bar-item w3-button">Link 2</a>
            <a href="insert javascript or url here" class="w3-bar-item w3-button">Link 3</a>
        </div>
      </div>
    </div>
   

    <!-- STATIC BODY CONTENT LEFT-->
    <!-- The main contents below the Navigation Bar which is always displayed on the page -->
    <div class="w3-container w3-twothird" id="main">

      <!-- SEARCH BAR -->
      <!-- Here is the search form for user input, pressing the "search" button calls the php code within this same page (action="...$_SERVER["PHP_SELF"]);?>"). References in the PHP by the tag "searchText" -->
      <!-- htmlspecialchars is being used here for security to prevent SQL injections -->
      <form class="w3-container" method="get" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
        <br>
        <label class="w3-text-red"><b>Looking for a restaurant?</b></label>
            <input class="w3-input w3-border w3-animate-input w3-hover-light-grey" name="searchText" type="text" style="width:30%" placeholder="search query">
            <!-- Category options for the type of restaurant -->
            <select class="w3-select" name="category">
                <option value="" disabled selected>Choose a category if you wish</option>
                <option value="Chinese">Chinese</option>
                <option value="Indian">Indian</option>
                <option value="Italian">Italian</option>
                <option value="Japanese">Japanese</option>
                <!--<option value="Mexican">Mexican</option>-->
                <option value="Western">Western</option>
            </select>
            <!-- Category options for the type of restaurant -->
            <select class="w3-select" name="category2">
                <option value="" disabled selected>Sorting options</option>
                <option value="name">Sort alphabetically</option>
                <option value="type">Sort by category</option>
            </select>
            <button class="w3-button w3-hover-shadow w3-round w3-theme">Search</button>
      </form>

      <!-- DYNAMIC CONTENT -->
      <!-- The main contents below the Static Body Content which is generated dynamically, as a result of searchers and user input. Dynamic content should be generated using PHP and the results of SQL queries -->

          <!-- RESULTS LIST -->
          <!-- The results of searching the database will be displayed here -->
          <br>
          <label class="w3-text-red"><b>Search results that match your query:</b></label>
          <?php 
            #the php code in this page points to a seperate php file that contains the code that perfoms the search of the SQL database. 

            #As the code of the seperate file is 'included' with this page any code/variables declared here will be combined with the code of the seperate php file. Variables to do not need to be passed explicitely.
            $callingPage = "index";
            $callingButton = $callingTab = $callingCategory = "";

            #Change the variable depending on what button was lasted pressed
            if($_SERVER['REQUEST_METHOD'] == "GET" and isset($_GET[test_button_1])){
              $callingButton = "test_button_1";
            }
            if($_SERVER['REQUEST_METHOD'] == "GET" and isset($_GET[test_button_2])){
              $callingButton = "test_button_2";
            }

            #Set the variables when an input is received
            if($_SERVER['REQUEST_METHOD'] == "GET"){
              $callingCategory = "";
              $callingCategory = test_input($_GET[category]);
              $callingCategory2 = "";
              $callingCategory2 = test_input($_GET[category2]);
            }

            #Cleans up the value before using as variable
            function test_input($data){
              $data = trim($data);
              $data = stripslashes($data);
              $data = htmlspecialchars($data);
              return $data;
            }

            #In this way we can recylce the search handler.
            include 'handle_search.php';
          ?>

    </div>



    <!-- STATIC BODY CONTENT RIGHT-->
    <!-- The main contents below the Navigation Bar which is always displayed on the page -->
    <div class="w3-container w3-third">

        <!-- The images of the automatic slideshow -->
        <div class="w3-content w3-section" style="max-width:500px">
            <img class="slideshow_restaurant_generic" src="images/rest_generic_001.png" style="width:100%">
            <img class="slideshow_restaurant_generic" src="images/rest_generic_002.png" style="width:100%">
            <img class="slideshow_restaurant_generic" src="images/rest_generic_003.png" style="width:100%">
            <img class="slideshow_restaurant_generic" src="images/rest_generic_004.png" style="width:100%">
            <img class="slideshow_restaurant_generic" src="images/rest_generic_005.png" style="width:100%">
        </div>

        <!-- The button which toggles the pop-up to add a restaurant -->
        <img onclick="document.getElementById('add_restaurant').style.display='block'" class="w3-center w3-btn w3-circle" src="images/submit-icon-1.png" style="width:25%">
        ADD a new Restaurant


              <!-- ADD NEW RESTAURANT POP-UP-->
              <!-- The contents of the 'add new restaurant' pop-up -->
              <div id="add_restaurant" class="w3-modal">
                <div class="w3-modal-content w3-card-4">

                    <!-- Header for the 'add restaurant' pop-up -->
                    <header class="w3-container w3-theme-d1">
                        <!-- Button to close the pop -->
                        <span onclick="document.getElementById('add_restaurant').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                        <h2>
                          <img src="images/submit-icon-1.png" alt="Icon for submissions" style="width: 55px; height: 55px;">
                          Add Restaurant 
                        </h2>
                    </header>

                    <!-- Main contents for the 'add restaurant' pop-up -->
                    <!-- Form for user to enter new restaurant data with required fields -->
                    <div class="w3-container">
                      <form class="w3-container" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method="post">

                        <div class="w3-section">
                          <label><b>Name</b></label>
                          <input class="w3-input w3-border w3-margin-bottom" name="submit_add_restaurant_name" type="text" placeholder="Enter restaurant name" required>
                          <label><b>Type</b></label>
                          <input class="w3-input w3-border w3-margin-bottom" name="submit_add_restaurant_type" type="text" placeholder="Western / Chinese / Indian ..." required>
                          <label><b>URL</b></label>
                          <input class="w3-input w3-border w3-margin-bottom" name="submit_add_restaurant_url" type="text" placeholder="www.deepcan.com" required>
                        </div>

                        <!-- Button to submit new restaurant data -->
                        <button class="w3-button w3-hover-shadow w3-round w3-theme" type="submit" name="submit_add_restaurant" value="submit_add_restaurant">Submit Restaurant</button>

                      </form>
                      <br>

                    </div>
                </div>
              </div>


        <!-- TEST BUTTONS -->
        <!-- Proof of concept, button presses change PHP variables to be used in the search handler switch case -->
        <br>
        <br>
        <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method="get">
            <button class="w3-button w3-hover-shadow w3-round w3-theme" name="test_button_1" value="test_button_1">Button_1</button>
            <button class="w3-button w3-hover-shadow w3-round w3-theme" name="test_button_2" value="test_button_2">Button_2</button>
        </form>
        <br>


        <!-- ADD RESTAURANT EXECUTION -->
        <?php 
            #the php code in this page points to a seperate php file that contains the code that perfoms the search of the SQL database. 

            #As the code of the seperate file is 'included' with this page any code/variables declared here will be combined with the code of the seperate php file. Variables to do not need to be passed explicitely.
            $callingPage = "index";
            $callingButton = $callingTab = $callingCategory = "";

            #Change the variable depending on what button was lasted pressed
            if($_SERVER['REQUEST_METHOD'] == "POST" and isset($_POST[submit_add_restaurant])){
              $callingButton = "submit_add_restaurant";
            }

            #In this way we can recylce the search handler.
            include 'handle_insertion.php';
          ?>


          <!-- AVERAGE PRICES BAR GRAPH -->
          <div id="top_in_category" class="w3-container w3-border tab">

              <h2>E</h2>
              <?php 
                #the php code in this page points to a seperate php file that peforms that actual search of the SQL database. 
                #In this way we can recylce the search handler.
                $callingPage = "indexRight";
                $callingTab = "";
                $callingButton = "";

                #Set the variables when an input is 
                if($_SERVER['REQUEST_METHOD'] == "GET"){
                  $callingCategory = "";
                  $callingCategory = test_input($_GET[category]);
                }

                include 'handle_search.php';
              ?>
          </div>


    </div>

  

    <!-- FOOTER -->
    <!-- The contents of the footer at the bottom of the webpage -->
    <div class="w3-row w3-container">  
      <footer class="w3-container w3-center w3-theme">
        <h5>Copyright &copy; DeepCan.com</h5>
        <p class="w3-opacity">Jonathan Calles (8906650) and Ahmed Haj Abdel Khaleq (8223727)</p>
      </footer>
    </div>



    <!-- AUTOMATIC SLIDESHOW -->
    <!-- This javascript supports the automatic slideshow. -->
    <!-- Reference: https://www.w3schools.com/w3css/w3css_slideshow.asp -->
    <script>
    var myIndex = 0;
    carousel();
    function carousel() {
        var i;
        var x = document.getElementsByClassName("slideshow_restaurant_generic");
        for (i = 0; i < x.length; i++) {
           x[i].style.display = "none";  
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}    
        x[myIndex-1].style.display = "block";  
        setTimeout(carousel, 2000); // Change image every 2 seconds
    }
    </script>


  </body>


</html>